### ISSUE TITLE
Add summary and table of contents

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#12]
Review this repo and 
- [x] Ensure that if people are just skimming, they still understand the major points
- [x] Add table of contents for a quick view of what is in the repo - this provides people with context and lets them know that they can't stop half way down because there's still important stuff to come.

**Comment by iteles** [comment]
https://github.com/dwyl/contributing/commit/706f3515c38c4ce0f763afcc13a1048a164df23c#diff-04c6e90faac2675aa89e2176d2eec7d8L10

**Comment by nelsonic** [comment]
@iteles I (_respectfully_) ***disagree*** that a Table Of contents _helps_ people skim-read the content... 
We _had_ a ToC and ***nobody*** followed the process. 😢 

What we _need_ is a _workflow_ diagram: https://github.com/dwyl/contributing/issues/17
so that we can _print_ it out on an A1 Poster in the office and give everyone a "Cheat Sheet".

**Comment by iteles** [comment]
To be fair the ToC was incomplete and didn't reflect the process, but that's why the discuss label is here! :+1:

**Comment by nelsonic** [comment]
we've now _removed_ the ToC as it was out-of-date and the content "_flows_" without it.
if anyone _prefers_ to have a ToC, please PR it back in. thanks.
