### ISSUE TITLE
Question about path/to/files/for/linting

### ISSUE THREAD

**Issue by martinsvajdlenka** [dwyl/contributing#124]
Hi team, thank you for great project.

I have question regarding "lint": "node_modules/.bin/goodparts path/to/files/for/linting", the 2nd path argument there that is mentioned in README.
I have my sources under src directory in the project and those sources are in many subdirectories.

When I run "npm run lint" it behaves different on my local env and server env. 
a. When I set path to "src" it is not working, same for "src/"
b. "src/\*" is working on my local repository, but not on the server ("ls src" works fine on the server, the files are present there). On local env it works, but it ignores files in subdirectories.
c. "\*" also works on local dev, but it ignores files in subdirectories. On server env it is failing on non-js files like README.md

So the questions are:
1. is there any path parameter that would check files also in subdirectories?
2. is there any setting to ignore non-js files like README.md?
Thank you for any help.

**Comment by iteles** [comment]
Hi @martinsvajdlenka, I suspect you may have opened this issue in a different repository to the one you expected to open it in, as there is no code in _this_ repo!

Please could you close this issue and open it again on the repository/tutorial that you were working through, so that someone in the community can help you out?

Thank you!
